### PR TITLE
36 implement user info customization page and successful login page

### PR DESCRIPTION
**Pull request by mbjaghou**

### CODE REVIEW

**Review by youssefachehboune — CHANGES_REQUESTED** [review]
- Update the title of the document 
- Update the country list, must be sorted (a-z)
- When the user selects an avatar from the suggested avatars, they must have the right to go back to their old avatar
- The username must be a maximum of 15 characters (enforce additional rules, such as allowing only alphanumeric characters (a-z, A-Z, 0-9) )
- The bio must be a maximum of 200 characters (enforce additional rules, such as allowing only alphanumeric characters (a-z, A-Z, 0-9) )
- Update the font-family: it must be "sora, sans-serif" in all texts on pages, following the styling from Figma
- Remove the cursor style in text-input and select
- Update the posistion of icon in select country
- Set "user-select" to "none" for non-text elements

**Review by youssefachehboune — CHANGES_REQUESTED** [review]
Add (*) to indicate required fields in all input elements

**Review by youssefachehboune — CHANGES_REQUESTED** [review]
-  Updating API Fetch

**Comment by mbjaghou** [comment]
all done

**Review by eassamer — APPROVED** [review]
good work mbjaghou

**Pull request merged**
